# Site settings
title: Cornell CSE
email: bindel@cornell.edu
description: >
  Web site of the Cornell CSE field.
baseurl: "/"
url: "http://www.cse.cornell.edu"
exclude: ["Rakefile", "README.md"]

#encoding: utf-8
encoding: ASCII-8BIT
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      footer: footer.html
      layout: sidebars
      title: Program in Computational Science and Engineering

cu_theme: "/cu_css"

encoding: utf-8
timezone: America/New_York

# Build settings
markdown: kramdown
