# Site settings
title: Cornell CSE
email: bindel@cornell.edu
description: >
  Web site of the Cornell CSE field.
baseurl: "/"
url: "https://cornell-cse.github.io"
exclude: ["Rakefile", "README.md"]

encoding: utf-8
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      footer: footer.html
      layout: default
      title: Program in Computational Science and Engineering

# Build settings
markdown: kramdown
